export const ACTIONS = {
    CHECK_INPUT: 'CHECK_INPUT',
    PII_DETECTED: 'PII_DETECTED',
    GET_STATS: 'GET_STATS',
    CLEAR_STATS: 'CLEAR_STATS',
    ADD_EXPOSED_WEBSITE: 'ADD_EXPOSED_WEBSITE',
    GET_EXPOSED_WEBSITES: 'GET_EXPOSED_WEBSITES',
    CLEAR_EXPOSED_WEBSITES: 'CLEAR_EXPOSED_WEBSITES',
    CHECK_WEBSITE_INTEGRITY: 'CHECK_WEBSITE_INTEGRITY'
};

export const PII_TYPES = {
    NIC: 'Sri Lankan NIC',
    CREDIT_CARD: 'Payment Card',
    PHONE: 'Phone Number',
    EMAIL: 'Email Address' 
};